---
- include: setup-redhat.yml
  when: ansible_os_family == "RedHat"

- name: enable and start xinetd
  service: name=xinetd enabled=yes state=started

- name: create omdistro site
  command: omd create {{ omdistro_site }} creates=/opt/omd/sites/{{ omdistro_site }}

- name: start omd
  service: name=omd state=started enabled=yes

- name: template hosts.mk
  template: >
      src=hosts.mk.j2
      dest=/opt/omd/sites/{{ omdistro_site }}/etc/check_mk/conf.d/hosts.mk
      owner={{ omdistro_site }}
      group={{ omdistro_site }}
      backup=yes
  notify: cmk inventory

- name: template groups.mk
  template: >
      src=groups.mk.j2
      dest=/opt/omd/sites/{{ omdistro_site }}/etc/check_mk/conf.d/groups.mk
      owner={{ omdistro_site }}
      group={{ omdistro_site }}
      backup=yes
  notify: cmk reload

- name: template main.mk
  template: >
      src=main.mk.j2
      dest=/opt/omd/sites/{{ omdistro_site }}/etc/check_mk/main.mk
      owner={{ omdistro_site }}
      group={{ omdistro_site }}
      backup=yes
  notify: cmk reload

- name: scan for parent/child relationships
  command: su -c "cmk --scan-parents" -l {{omdistro_site}}
  when: omdistro_scan_parents
