---
- name: template consol labs yum repository
  template: src=consol-labs.repo.j2 dest=/etc/yum.repos.d/consol-labs.repo

- name: import consol labs rpm key
  rpm_key: key={{omdistro_consol_labs_rpm_key}} state=present

- name: install omdistro and check-mk-agent
  yum: name={{ item }} state=installed
  notify: restart xinetd
  with_items:
    - omd-{{ omdistro_version }}
    - check-mk-agent
    - mod_ssl
